"""Bind helper functions from split modules back into one namespace.

This lets `main.py` stay short while older code can still call familiar helper
names like `is_target_location()` or `compute_roi_score()`.
"""

from pipeline import core_helpers
from pipeline import evaluation
from pipeline import normalization
from pipeline import policy
from pipeline import runtime_ops
from pipeline import scoring_helpers
from pipeline import source_feedback
from pipeline import title_rules


def install_bound_helpers(target_globals, ctx):
    """Attach bound helper functions to the given module globals."""
    target_globals.update(
        {
            "has_cyber_anchor": lambda title: title_rules.has_cyber_anchor(title, ctx=ctx),
            "is_cyber_analyst_title": lambda title: title_rules.is_cyber_analyst_title(title, ctx=ctx),
            "is_cyber_investigator_title": lambda title: title_rules.is_cyber_investigator_title(title, ctx=ctx),
            "is_engineering_heavy_cyber_title": lambda title: title_rules.is_engineering_heavy_cyber_title(title, ctx=ctx),
            "is_specialized_security_engineering_title": lambda title: title_rules.is_specialized_security_engineering_title(title, ctx=ctx),
            "is_blue_team_cyber_title": lambda title: title_rules.is_blue_team_cyber_title(title, ctx=ctx),
            "is_soc_focused_title": lambda title: title_rules.is_soc_focused_title(title, ctx=ctx),
            "has_excluded_cyber_title_terms": lambda title: title_rules.has_excluded_cyber_title_terms(title, ctx=ctx),
            "is_target_soc_role_title": lambda title: title_rules.is_target_soc_role_title(title, ctx=ctx),
            "is_target_cyber_analyst_role_title": lambda title: title_rules.is_target_cyber_analyst_role_title(title, ctx=ctx),
            "is_target_it_role_title": lambda title: title_rules.is_target_it_role_title(title, ctx=ctx),
            "is_implicit_aggregator_it_role": lambda job: title_rules.is_implicit_aggregator_it_role(job, ctx=ctx),
            "has_aggregator_support_title": lambda title: title_rules.has_aggregator_support_title(title, ctx=ctx),
            "get_path_tier_label": lambda job, track_name: title_rules.get_path_tier_label(job, track_name, ctx=ctx),
            "has_disqualifying_cyber_seniority": lambda title: title_rules.has_disqualifying_cyber_seniority(title, ctx=ctx),
            "fails_entry_level_cyber_gate": lambda job, resume_text, track_name="": title_rules.fails_entry_level_cyber_gate(
                job,
                resume_text,
                track_name,
                ctx=ctx,
            ),
            "has_junior_title_signal": lambda title: title_rules.has_junior_title_signal(title, ctx=ctx),
            "compute_title_fit_score": lambda job, track_name: title_rules.compute_title_fit_score(job, track_name, ctx=ctx),
            "is_new_york_location": lambda job: policy.is_new_york_location(job, ctx=ctx),
            "is_target_location": lambda job: policy.is_target_location(job, ctx=ctx),
            "has_explicit_us_remote_signal": lambda job: policy.has_explicit_us_remote_signal(job, ctx=ctx),
            "is_us_location": lambda job: policy.is_us_location(job, ctx=ctx),
            "is_geo_ambiguous_us_region": lambda job: policy.is_geo_ambiguous_us_region(job, ctx=ctx),
            "is_priority_queue_location": lambda job: policy.is_priority_queue_location(job, ctx=ctx),
            "is_physical_security": lambda text: policy.is_physical_security(text, ctx=ctx),
            "get_company_difficulty": lambda company_id: policy.get_company_difficulty(company_id, ctx=ctx),
            "get_role_difficulty_modifier": lambda job, track_name: policy.get_role_difficulty_modifier(job, track_name, ctx=ctx),
            "detect_junior_plus": lambda job: policy.detect_junior_plus(job, ctx=ctx),
            "detect_competition_magnetism": lambda job, track_name, company_difficulty: policy.detect_competition_magnetism(
                job,
                track_name,
                company_difficulty,
                ctx=ctx,
            ),
            "get_company_target_profile": lambda company_id="", company_group_hint="", metadata_hint=None: policy.get_company_target_profile(
                company_id,
                company_group_hint,
                metadata_hint,
                ctx=ctx,
            ),
            "detect_hidden_requirement_signals": lambda text: policy.detect_hidden_requirement_signals(text, ctx=ctx),
            "get_stepping_stone_label": lambda job, track_name: scoring_helpers.get_stepping_stone_label(job, track_name, ctx=ctx),
            "compute_entry_viability_score": lambda job, track_name, fit_result, acceptance_result, execution_result, trajectory_result, target_signal_result, narrative_result, stepping_stone_label: scoring_helpers.compute_entry_viability_score(
                job,
                track_name,
                fit_result,
                acceptance_result,
                execution_result,
                trajectory_result,
                target_signal_result,
                narrative_result,
                stepping_stone_label,
                ctx=ctx,
            ),
            "compute_response_likelihood_score": lambda job, acceptance_result, execution_result, narrative_result, target_signal_result, entry_viability_result: scoring_helpers.compute_response_likelihood_score(
                job,
                acceptance_result,
                execution_result,
                narrative_result,
                target_signal_result,
                entry_viability_result,
                ctx=ctx,
            ),
            "compute_apply_priority_score": lambda job, fit_result, acceptance_result, trajectory_result, entry_viability_result, response_likelihood_result: scoring_helpers.compute_apply_priority_score(
                job,
                fit_result,
                acceptance_result,
                trajectory_result,
                entry_viability_result,
                response_likelihood_result,
                ctx=ctx,
            ),
            "get_source_adjusted_thresholds": lambda job, track_name, mode, base_fit, base_final: scoring_helpers.get_source_adjusted_thresholds(
                job,
                track_name,
                mode,
                base_fit,
                base_final,
                ctx=ctx,
            ),
            "compute_source_adjusted_final_score": lambda job, fit_result, acceptance_result, execution_result, trajectory_result, narrative_result, roi_result, target_signal_result, entry_viability_result, response_likelihood_result: scoring_helpers.compute_source_adjusted_final_score(
                job,
                fit_result,
                acceptance_result,
                execution_result,
                trajectory_result,
                narrative_result,
                roi_result,
                target_signal_result,
                entry_viability_result,
                response_likelihood_result,
                ctx=ctx,
            ),
            "compute_narrative_fit": lambda job, track_name: scoring_helpers.compute_narrative_fit(job, track_name, ctx=ctx),
            "compute_effort_score": lambda job, track_name, fit_result, acceptance_result, execution_result, narrative_result: scoring_helpers.compute_effort_score(
                job,
                track_name,
                fit_result,
                acceptance_result,
                execution_result,
                narrative_result,
                ctx=ctx,
            ),
            "compute_roi_score": lambda fit_result, acceptance_result, execution_result, trajectory_result, narrative_result, effort_result: scoring_helpers.compute_roi_score(
                fit_result,
                acceptance_result,
                execution_result,
                trajectory_result,
                narrative_result,
                effort_result,
                ctx=ctx,
            ),
            "choose_decision": lambda roi_score, fit_score, acceptance_score, execution_score, narrative_score, difficulty_tier: scoring_helpers.choose_decision(
                roi_score,
                fit_score,
                acceptance_score,
                execution_score,
                narrative_score,
                difficulty_tier,
                ctx=ctx,
            ),
            "build_risk_notes": lambda acceptance_result, execution_result, narrative_result, effort_result: scoring_helpers.build_risk_notes(
                acceptance_result,
                execution_result,
                narrative_result,
                effort_result,
                ctx=ctx,
            ),
            "get_execution_tier": lambda score: scoring_helpers.get_execution_tier(score, ctx=ctx),
            "compute_execution_score": lambda job, track_name, resume_text, fit_result: evaluation.compute_execution_score(
                job,
                track_name,
                resume_text,
                fit_result,
                ctx=ctx,
            ),
            "compute_trajectory_score": lambda job, track_name, fit_result: evaluation.compute_trajectory_score(job, track_name, fit_result, ctx=ctx),
            "compute_target_signal": lambda job: evaluation.compute_target_signal(job, ctx=ctx),
            "extract_required_years": lambda text: evaluation.extract_required_years(text, ctx=ctx),
            "is_early_career": lambda job: evaluation.is_early_career(job, ctx=ctx),
            "detect_disguised_mid_level": lambda job: evaluation.detect_disguised_mid_level(job, ctx=ctx),
            "detect_missing_certs": lambda job_text, resume_text, track_name: evaluation.detect_missing_certs(
                job_text,
                resume_text,
                track_name,
                ctx=ctx,
            ),
            "parse_timestamp": lambda value: normalization.parse_timestamp(value, ctx=ctx),
            "format_runtime": lambda seconds: normalization.format_runtime(seconds, ctx=ctx),
            "format_days_old": lambda days_old: normalization.format_days_old(days_old, ctx=ctx),
            "get_freshness_priority_score": lambda job: normalization.get_freshness_priority_score(job, ctx=ctx),
            "compute_freshness": lambda posted_at, updated_at: normalization.compute_freshness(posted_at, updated_at, ctx=ctx),
            "normalize": lambda job: normalization.normalize(job, ctx=ctx),
            "dedupe_jobs": lambda jobs: normalization.dedupe_jobs(jobs, ctx=ctx),
            "ensure_results_dir": lambda: runtime_ops.ensure_results_dir(ctx=ctx),
            "get_snapshot_archive_path": lambda name: runtime_ops.get_snapshot_archive_path(name, ctx=ctx),
            "get_result_destination_path": lambda name: runtime_ops.get_result_destination_path(name, ctx=ctx),
            "migrate_existing_results": lambda: runtime_ops.migrate_existing_results(ctx=ctx),
            "load_resumes": lambda: runtime_ops.load_resumes(ctx=ctx),
            "load_cache": lambda: runtime_ops.load_cache(ctx=ctx),
            "save_cache": lambda jobs: runtime_ops.save_cache(jobs, ctx=ctx),
            "load_company_effectiveness": lambda: runtime_ops.load_company_effectiveness(ctx=ctx),
            "save_company_effectiveness": lambda companies: runtime_ops.save_company_effectiveness(companies, ctx=ctx),
            "get_company_effectiveness_profile": lambda company_id: runtime_ops.get_company_effectiveness_profile(company_id, ctx=ctx),
            "should_skip_external_source": lambda source: runtime_ops.should_skip_external_source(source, ctx=ctx),
            "summarize_source_mix": lambda raw_jobs: runtime_ops.summarize_source_mix(raw_jobs, ctx=ctx),
            "collect_jobs": lambda: runtime_ops.collect_jobs(ctx=ctx),
            "update_run_metadata": lambda scrape_duration_seconds, source_mix=None: runtime_ops.update_run_metadata(
                scrape_duration_seconds,
                source_mix,
                ctx=ctx,
            ),
            "is_cyber_track": lambda track_name: core_helpers.is_cyber_track(track_name, ctx=ctx),
            "is_soc_track": lambda track_name: core_helpers.is_soc_track(track_name, ctx=ctx),
            "is_cyber_analyst_track": lambda track_name: core_helpers.is_cyber_analyst_track(track_name, ctx=ctx),
            "is_it_track": lambda track_name: core_helpers.is_it_track(track_name, ctx=ctx),
            "get_resume_for_track": lambda resumes, track_name: core_helpers.get_resume_for_track(resumes, track_name, ctx=ctx),
            "get_skill_profile": lambda track_name: core_helpers.get_skill_profile(track_name, ctx=ctx),
            "contains_any": lambda text, terms: core_helpers.contains_any(text, terms, ctx=ctx),
            "matches_any_pattern": lambda text, patterns: core_helpers.matches_any_pattern(text, patterns, ctx=ctx),
            "count_matching_terms": lambda text, terms: core_helpers.count_matching_terms(text, terms, ctx=ctx),
            "is_internship_like": lambda job: core_helpers.is_internship_like(job, ctx=ctx),
            "is_internship_target_location": lambda job: core_helpers.is_internship_target_location(job, ctx=ctx),
            "update_company_effectiveness": lambda raw_jobs, jobs_by_track: source_feedback.update_company_effectiveness(
                raw_jobs,
                jobs_by_track,
                ctx=ctx,
            ),
        }
    )
