from shared.utils import normalize_company_id


def build_source(
    *,
    name,
    provider,
    tags,
    difficulty="standard",
    hiring_pattern="steady",
    industry="mixed",
    max_jobs=60,
    **extra,
):
    source = {
        "id": normalize_company_id(f"aggregator:{provider}:{name}"),
        "name": name,
        "provider": provider,
        "tags": sorted({str(tag).strip().lower() for tag in tags if str(tag).strip()}),
        "difficulty": difficulty,
        "hiring_pattern": hiring_pattern,
        "industry": industry,
        "max_jobs": max_jobs,
    }
    source.update(extra)
    return source


AGGREGATOR_SOURCES = [
    build_source(
        name="Remotive US Remote",
        provider="remotive",
        tags=["aggregator", "remote-friendly", "broad-market"],
        difficulty="standard",
        hiring_pattern="steady",
        industry="mixed",
        max_jobs=140,
        allow_in_combined_text=True,
        search_terms=[
            "security analyst",
            "soc",
            "incident response",
            "threat",
            "technical support",
            "application support",
            "it support",
            "help desk",
            "service desk",
            "desktop support",
            "support engineer",
            "platform support",
            "product support analyst",
            "technical operations",
            "customer experience engineer",
            "operations assistant",
            "identity access",
            "trust and safety",
            "fraud analyst",
        ],
        title_allow_terms=[
            "security operations",
            "security analyst",
            "soc",
            "incident response",
            "threat",
            "detection",
            "technical support",
            "application support",
            "it support",
            "systems support",
            "support specialist",
            "support engineer",
            "customer experience",
            "customer advocate",
            "product support",
            "platform support",
            "technical operations",
            "operations assistant",
            "experience specialist",
            "desktop support",
            "help desk",
            "service desk",
            "operator",
            "identity",
            "access",
            "iam",
            "trust",
            "fraud",
            "investigations",
            "noc",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "staff ",
            "principal",
            "manager",
            "director",
            "architect",
            "sales",
            "account executive",
            "customer success",
            "customer support representative",
            "customer service representative",
            "call center",
        ],
        location_allow_terms=["usa", "united states", "us only", "north america"],
        location_block_terms=[
            "worldwide",
            "europe",
            "emea",
            "latam",
            "asia",
            "canada",
            "australia",
            "india",
            "uk",
            "united kingdom",
        ],
    ),
    build_source(
        name="Remote OK Bridge Feed",
        provider="remoteok",
        tags=["aggregator", "broad-market", "remote-friendly"],
        difficulty="standard",
        hiring_pattern="steady",
        industry="mixed",
        max_jobs=140,
        allow_in_combined_text=True,
        title_allow_terms=[
            "support",
            "customer",
            "community",
            "operations",
            "specialist",
            "coordinator",
            "technician",
            "analyst",
            "security operations",
            "security analyst",
            "incident response",
            "threat",
            "technical support",
            "support engineer",
            "support specialist",
            "support operator",
            "customer advocate",
            "experience",
            "platform support",
            "product support",
            "technical operations",
            "operations assistant",
            "desktop support",
            "help desk",
            "service desk",
            "identity",
            "access",
            "iam",
            "trust",
            "fraud",
            "investigations",
            "noc",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "lead ",
            "manager",
            "director",
            "architect",
            "sales",
            "customer success manager",
            "vice president",
            "principal",
            "software engineer",
            "growth designer",
        ],
        location_allow_terms=[
            "remote",
            "new york",
            "united states",
            "usa",
            "texas",
            "dallas",
        ],
        location_block_terms=[
            "greece",
            "europe",
            "emea",
            "canada",
            "india",
            "uk",
            "united kingdom",
            "australia",
            "mexico",
        ],
    ),
    build_source(
        name="The Muse Bridge Feed",
        provider="themuse",
        tags=["aggregator", "broad-market", "enterprise-leaning"],
        difficulty="standard",
        hiring_pattern="steady",
        industry="mixed",
        max_jobs=80,
        page_limit=120,
        allow_in_combined_text=True,
        title_allow_terms=[
            "support",
            "specialist",
            "coordinator",
            "technician",
            "analyst",
            "operations",
            "it/av support",
            "support coordinator",
            "technical support",
            "application support",
            "customer experience",
            "customer advocate",
            "platform support",
            "product support",
            "technical operations",
            "operations assistant",
            "experience specialist",
            "service desk",
            "help desk",
            "identity",
            "access",
            "iam",
            "cyber security specialist",
            "security analyst",
            "incident",
            "fraud",
            "trust",
            "investigations",
            "field support",
            "operations specialist",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "lead ",
            "manager",
            "director",
            "architect",
            "principal",
            "vice president",
            "registered nurse",
            "physician",
            "sales",
            "officer",
            "security host",
            "security guard",
            "ranger",
            "banker",
            "advisor development",
            "account representative",
            "housekeeping",
            "maintenance",
            "administrative",
        ],
        location_block_terms=[
            "europe",
            "emea",
            "canada",
            "india",
            "uk",
            "united kingdom",
            "australia",
            "mexico",
        ],
    ),
    build_source(
        name="Jobicy Support Feed",
        provider="jobicy",
        tags=["aggregator", "remote-friendly", "broad-market"],
        difficulty="standard",
        hiring_pattern="steady",
        industry="mixed",
        max_jobs=70,
        request_count=180,
        allow_in_combined_text=True,
        api_tag="support",
        title_allow_terms=[
            "support",
            "customer",
            "specialist",
            "coordinator",
            "technician",
            "analyst",
            "technical support",
            "support analyst",
            "production support",
            "support engineer",
            "customer advocate",
            "platform support",
            "product support",
            "technical operations",
            "operations assistant",
            "experience specialist",
            "service desk",
            "help desk",
            "it support",
            "application support",
            "customer support specialist",
            "technical support analyst",
            "identity",
            "access",
            "iam",
            "security analyst",
            "incident",
            "fraud",
            "trust",
            "investigations",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "lead ",
            "manager",
            "director",
            "architect",
            "principal",
            "vice president",
            "sales",
            "customer support team lead",
            "call center",
        ],
        location_block_terms=[
            "portugal",
            "europe",
            "emea",
            "canada",
            "australia",
            "india",
            "uk",
            "united kingdom",
            "poland",
            "mexico",
            "ukraine",
            "spain",
            "germany",
        ],
    ),
    build_source(
        name="We Work Remotely Support Feed",
        provider="weworkremotely",
        tags=["aggregator", "remote-friendly", "broad-market"],
        difficulty="standard",
        hiring_pattern="steady",
        industry="mixed",
        max_jobs=60,
        allow_in_combined_text=True,
        url="https://weworkremotely.com/categories/remote-customer-support-jobs",
        title_allow_terms=[
            "support",
            "customer",
            "community",
            "specialist",
            "coordinator",
            "technician",
            "analyst",
            "technical support",
            "customer support",
            "community support",
            "support analyst",
            "support engineer",
            "service desk",
            "help desk",
            "it support",
            "application support",
            "support specialist",
            "tech support",
            "customer advocate",
            "customer experience",
            "platform support",
            "product support",
            "technical operations",
            "operations assistant",
            "experience specialist",
            "identity",
            "access",
            "iam",
            "security analyst",
            "incident",
            "fraud",
            "trust",
            "investigations",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "lead ",
            "manager",
            "director",
            "architect",
            "principal",
            "vice president",
            "sales",
            "customer service agent",
            "bilingual customer service",
            "head of support",
            "customer success manager",
        ],
        location_block_terms=[
            "bulgaria",
            "cyprus",
            "estonia",
            "hungary",
            "lithuania",
            "latvia",
            "poland",
            "romania",
            "serbia",
            "slovakia",
            "ukraine",
            "canada",
            "portugal",
        ],
    ),
    build_source(
        name="We Work Remotely Tech Support Feed",
        provider="weworkremotely",
        tags=["aggregator", "remote-friendly", "broad-market"],
        difficulty="standard",
        hiring_pattern="steady",
        industry="mixed",
        max_jobs=80,
        allow_in_combined_text=True,
        url="https://weworkremotely.com/categories/remote-tech-support-jobs",
        title_allow_terms=[
            "support",
            "technical support",
            "tech support",
            "platform support",
            "product support",
            "customer experience",
            "customer advocate",
            "support engineer",
            "support specialist",
            "service desk",
            "help desk",
            "it support",
            "application support",
            "technical operations",
            "operations assistant",
            "systems support",
            "identity",
            "access",
            "iam",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "lead ",
            "manager",
            "director",
            "architect",
            "principal",
            "vice president",
            "sales",
            "head of support",
            "customer success manager",
        ],
        location_block_terms=[
            "bulgaria",
            "cyprus",
            "estonia",
            "hungary",
            "lithuania",
            "latvia",
            "poland",
            "romania",
            "serbia",
            "slovakia",
            "ukraine",
            "canada",
            "portugal",
        ],
    ),
    build_source(
        name="We Work Remotely All Other Bridge Feed",
        provider="weworkremotely",
        tags=["aggregator", "remote-friendly", "broad-market"],
        difficulty="standard",
        hiring_pattern="steady",
        industry="mixed",
        max_jobs=80,
        allow_in_combined_text=True,
        url="https://weworkremotely.com/categories/remote-all-other-remote-jobs",
        title_allow_terms=[
            "support",
            "specialist",
            "coordinator",
            "analyst",
            "operations",
            "technical support",
            "platform support",
            "product support",
            "customer advocate",
            "customer experience",
            "support engineer",
            "service desk",
            "help desk",
            "it support",
            "application support",
            "identity",
            "access",
            "iam",
            "trust",
            "fraud",
            "investigations",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "lead ",
            "manager",
            "director",
            "architect",
            "principal",
            "vice president",
            "sales",
            "marketing",
            "account executive",
            "customer success manager",
        ],
        location_block_terms=[
            "bulgaria",
            "cyprus",
            "estonia",
            "hungary",
            "lithuania",
            "latvia",
            "poland",
            "romania",
            "serbia",
            "slovakia",
            "ukraine",
            "canada",
            "portugal",
        ],
    ),
    build_source(
        name="We Work Remotely DevOps Sysadmin Feed",
        provider="weworkremotely",
        tags=["aggregator", "remote-friendly", "broad-market"],
        difficulty="standard",
        hiring_pattern="steady",
        industry="mixed",
        max_jobs=70,
        allow_in_combined_text=True,
        url="https://weworkremotely.com/categories/remote-devops-sysadmin-jobs",
        title_allow_terms=[
            "support",
            "sysadmin",
            "systems",
            "operations",
            "platform",
            "it",
            "technical",
            "service desk",
            "help desk",
            "administrator",
            "identity",
            "access",
            "security",
            "noc",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "staff ",
            "principal",
            "manager",
            "director",
            "architect",
            "sales",
            "vice president",
            "lead ",
            "tech lead",
        ],
        location_allow_terms=[
            "usa",
            "united states",
            "us only",
            "north america",
            "new york",
            "remote",
        ],
        location_block_terms=[
            "europe",
            "emea",
            "latam",
            "asia",
            "canada",
            "uk",
            "united kingdom",
            "australia",
            "india",
        ],
    ),
]
