from shared.utils import normalize_company_id


def build_source(
    *,
    name,
    source_type,
    url,
    tags,
    difficulty,
    hiring_pattern,
    industry,
    max_jobs=25,
    max_detail_fetches=12,
    **extra,
):
    normalized_tags = sorted({str(tag).strip().lower() for tag in tags if str(tag).strip()})
    source = {
        "id": normalize_company_id(f"extended:{source_type}:{name}"),
        "name": name,
        "type": source_type,
        "url": url,
        "tags": normalized_tags,
        "difficulty": difficulty,
        "hiring_pattern": hiring_pattern,
        "industry": industry,
        "max_jobs": max_jobs,
        "max_detail_fetches": max_detail_fetches,
    }
    source.update(extra)
    return source


EXTENDED_SOURCES = [
    build_source(
        name="Experian",
        source_type="smartrecruiters",
        url="experian",
        tags=["direct-careers", "enterprise", "finance", "security"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=60,
        max_detail_fetches=25,
    ),
    build_source(
        name="Agile IT",
        source_type="smartrecruiters",
        url="agileit",
        tags=["direct-careers", "mssp", "security", "consulting"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="security",
        max_jobs=40,
        max_detail_fetches=20,
    ),
    build_source(
        name="blueStone",
        source_type="smartrecruiters",
        url="blueStone",
        tags=["direct-careers", "consulting", "security", "staffing"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="security",
        max_jobs=50,
        max_detail_fetches=25,
    ),
    build_source(
        name="FSR LLC",
        source_type="smartrecruiters",
        url="fsrllc",
        tags=["direct-careers", "consulting", "security", "gov-adjacent"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="security",
        max_jobs=40,
        max_detail_fetches=20,
    ),
    build_source(
        name="Frontier Technologies LLC",
        source_type="smartrecruiters",
        url="FrontierTechnologiesLLC1",
        tags=["direct-careers", "consulting", "security", "gov-adjacent"],
        difficulty="stretch",
        hiring_pattern="steady",
        industry="security",
        max_jobs=40,
        max_detail_fetches=20,
    ),
    build_source(
        name="Eikon Consulting",
        source_type="smartrecruiters",
        url="EikonConsulting",
        tags=["direct-careers", "consulting", "security"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="security",
        max_jobs=35,
        max_detail_fetches=20,
    ),
    build_source(
        name="Endava",
        source_type="smartrecruiters",
        url="endava",
        tags=["direct-careers", "consulting", "tech", "security"],
        difficulty="stretch",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=60,
        max_detail_fetches=25,
    ),
    build_source(
        name="AMNet Services",
        source_type="smartrecruiters",
        url="AMNetServicesInc",
        tags=["direct-careers", "msp", "it-services", "staffing", "enterprise", "entry-friendly"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="tech",
        max_jobs=40,
        max_detail_fetches=20,
        title_allow_terms=[
            "support",
            "service desk",
            "desktop",
            "systems analyst",
            "it project",
            "technical",
            "network",
            "technician",
            "administrator",
        ],
        title_block_terms=[
            "senior",
            "architect",
            "warehouse",
            "mechanical",
            "presentation",
            "publication",
            "marketing",
            "financial",
            "developer",
            "java",
            "quality management tester",
            "project manager",
            "designer",
            "coordinator",
            "supervisor",
        ],
    ),
    build_source(
        name="4DS Corp",
        source_type="smartrecruiters",
        url="4dscorp",
        tags=["direct-careers", "it-services", "service-desk", "entry-friendly", "local-ny"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=15,
        max_detail_fetches=10,
        title_allow_terms=[
            "technical support",
            "support specialist",
            "systems analyst",
            "administrator",
            "technician",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "director",
            "designer",
            "marketing",
            "sales",
            "accountant",
            "procurement",
            "business development",
            "creative",
            "mandarin",
            "marketplace",
            "brand",
            "ecommerce",
        ],
        location_allow_terms=[
            "new york",
            "ny",
            "hicksville",
            "remote",
            "united states",
            "usa",
        ],
    ),
    build_source(
        name="City of New York",
        source_type="smartrecruiters",
        url="CityOfNewYork",
        tags=["direct-careers", "gov-adjacent", "service-desk", "entry-friendly", "local-ny"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=6,
        max_detail_fetches=10,
        page_limit=30,
        title_allow_terms=[
            "tech support intern",
            "help desk support intern",
            "digital support intern",
        ],
        title_block_terms=[
            "analyst",
            "developer",
            "audit",
            "budget",
            "expense",
            "manager",
            "director",
            "attorney",
            "engineering",
            "data analyst",
        ],
        location_allow_terms=[
            "new york",
            "queens",
            "new york city",
        ],
    ),
    build_source(
        name="nfrastructure",
        source_type="smartrecruiters",
        url="nfrastructure",
        tags=["direct-careers", "it-services", "service-desk", "entry-friendly", "local-ny"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=8,
        max_detail_fetches=8,
        title_allow_terms=[
            "service desk analyst",
            "technical support",
            "support analyst",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "voip technician",
            "ambassador",
        ],
        location_allow_terms=[
            "buffalo",
            "new york",
            "ny",
        ],
    ),
    build_source(
        name="IPsoft",
        source_type="smartrecruiters",
        url="IPsoftInc1",
        tags=["direct-careers", "it-services", "service-desk", "entry-friendly", "local-ny"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=20,
        max_detail_fetches=12,
        title_allow_terms=[
            "help desk",
            "service desk",
            "support",
            "administrator",
            "technical support",
            "it support",
            "systems",
            "applications administrator",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "director",
            "architect",
            "sales",
            "developer",
            "staff accountant",
            "office administrator",
        ],
        location_allow_terms=[
            "new york",
            "ny",
            "remote",
            "united states",
            "usa",
        ],
    ),
    build_source(
        name="Collabera",
        source_type="smartrecruiters",
        url="Collabera6",
        tags=["direct-careers", "staffing", "service-desk", "entry-friendly", "local-ny"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="tech",
        max_jobs=6,
        max_detail_fetches=6,
        title_allow_terms=[
            "helpdesk associate analyst",
            "help desk analyst",
            "technical support analyst",
            "help desk services associate",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "business analyst",
            "salesforce",
            "implementation",
            "customer support technician",
        ],
        location_allow_terms=[
            "albany",
            "new york",
            "ny",
        ],
    ),
    build_source(
        name="360 IT Professionals",
        source_type="smartrecruiters",
        url="360ITProfessionals1",
        tags=["direct-careers", "staffing", "service-desk", "entry-friendly", "local-ny"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="tech",
        max_jobs=6,
        max_detail_fetches=6,
        title_allow_terms=[
            "technical support specialist",
            "helpdesk analyst",
            "desktop support specialist",
            "identity & access management analyst",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "business analyst",
            "quality analyst",
            "electrical",
            "mechanical",
            "oracle",
            "azure administrator",
            "video conferencing",
        ],
        location_allow_terms=[
            "albany",
            "new york",
            "ny",
        ],
    ),
    build_source(
        name="Artech",
        source_type="smartrecruiters",
        url="ArtechInformationSystemLLC",
        tags=["direct-careers", "staffing", "service-desk", "entry-friendly", "local-ny"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="tech",
        max_jobs=8,
        max_detail_fetches=8,
        title_allow_terms=[
            "desktop support",
            "it support specialist",
            "technical support specialist",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "director",
            "business analyst",
            "operations analyst",
            "pharmacy technician",
            "biomedical",
            "team lead",
            "representative",
        ],
        location_allow_terms=[
            "new york",
            "ny",
            "remote",
        ],
    ),
    build_source(
        name="Fortress SRM",
        source_type="smartrecruiters",
        url="MCPC",
        tags=["direct-careers", "mssp", "security", "consulting"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="security",
        max_jobs=35,
        max_detail_fetches=20,
    ),
    build_source(
        name="QBE LLC",
        source_type="smartrecruiters",
        url="QBELLC",
        tags=["direct-careers", "gov-adjacent", "security", "service-desk"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="security",
        max_jobs=35,
        max_detail_fetches=20,
    ),
    build_source(
        name="ADP",
        source_type="happydance",
        url="https://jobs.adp.com/en/jobs/",
        tags=["direct-careers", "enterprise", "security", "corporate"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=30,
        max_detail_fetches=10,
    ),
    build_source(
        name="TransUnion",
        source_type="workday",
        url="https://transunion.wd5.myworkdayjobs.com/wday/cxs/transunion/transunion/jobs",
        tags=["direct-careers", "enterprise", "finance", "remote-friendly"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=30,
        max_detail_fetches=20,
        search_terms=["desktop support", "it support", "application support", "technical analyst"],
        title_allow_terms=["it support", "application support", "desktop support", "technical analyst", "support technician", "technical support"],
        title_block_terms=["manager", "senior", "sales", "billing", "customer service", "executive", "advisor", "development", "administrator", "auditor", "consulting"],
        location_allow_terms=["chicago", "virginia", "new york", "new jersey", "usa", "united states", "remote"],
        location_block_terms=["mumbai", "bogota", "cape town", "ontario"],
        public_url_template="https://transunion.wd5.myworkdayjobs.com/en-US/transunion{external_path}",
    ),
    build_source(
        name="Alight",
        source_type="smartrecruiters",
        url="Alight",
        tags=["direct-careers", "enterprise", "service-desk", "hire-heavy"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="tech",
        max_jobs=50,
        max_detail_fetches=20,
    ),
    build_source(
        name="Leidos",
        source_type="workday",
        url="https://leidos.wd5.myworkdayjobs.com/wday/cxs/leidos/External/jobs",
        tags=["direct-careers", "gov-adjacent", "security", "hire-heavy"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="security",
        max_jobs=30,
        max_detail_fetches=20,
        search_terms=["cybersecurity analyst", "security analyst", "incident response analyst", "it support technician", "isso"],
        title_allow_terms=["analyst", "technician", "isso"],
        title_block_terms=["senior", "sr ", "sr.", "sme", "lead", "manager", "architect", "engineer", "director"],
        location_allow_terms=["virginia", "maryland", "washington", "dc", "new york", "new jersey", "pennsylvania", "remote"],
        public_url_template="https://leidos.wd5.myworkdayjobs.com/en-US/External{external_path}",
    ),
    build_source(
        name="Workday",
        source_type="workday",
        url="https://workday.wd5.myworkdayjobs.com/wday/cxs/workday/Workday/jobs",
        tags=["direct-careers", "tech", "remote-friendly", "saas"],
        difficulty="stretch",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=20,
        max_detail_fetches=20,
        search_terms=["technical support engineer", "customer support analyst", "application support"],
        title_allow_terms=["technical support engineer", "customer support analyst", "application support"],
        title_block_terms=["senior", "sr ", "sr.", "consultant", "manager", "architect", "director", "principal", "network engineer", "devops", "integration", "business development", "lead"],
        location_allow_terms=["usa", "united states", "new york", "new jersey", "virginia", "pennsylvania", "maryland"],
        location_block_terms=["poland", "costa rica", "india", "ireland", "israel", "canada"],
        public_url_template="https://workday.wd5.myworkdayjobs.com/en-US/Workday{external_path}",
    ),
    build_source(
        name="SHI",
        source_type="workday",
        url="https://shi.wd12.myworkdayjobs.com/wday/cxs/shi/shicareers/jobs",
        tags=["direct-careers", "enterprise", "it", "remote-friendly", "hire-heavy"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="tech",
        max_jobs=25,
        max_detail_fetches=20,
        search_terms=["cybersecurity advisor", "associate cybersecurity advisor", "support engineer", "technical support"],
        title_allow_terms=["cybersecurity advisor", "associate cybersecurity advisor", "support engineer", "technical support"],
        title_block_terms=["solutions engineer", "presales", "manager", "director", "intern", "software engineer", "cloud engineer", "field solutions engineer", "systems engineer", "idcs"],
        public_url_template="https://shi.wd12.myworkdayjobs.com/en-US/shicareers{external_path}",
    ),
    build_source(
        name="CrowdStrike",
        source_type="workday",
        url="https://crowdstrike.wd5.myworkdayjobs.com/wday/cxs/crowdstrike/CrowdStrikeCareers/jobs",
        tags=["direct-careers", "security", "vendor", "remote-friendly"],
        difficulty="stretch",
        hiring_pattern="steady",
        industry="security",
        max_jobs=20,
        max_detail_fetches=20,
        search_terms=["analyst i", "falcon complete", "threat analyst", "data protection analyst"],
        title_allow_terms=["falcon complete", "threat analyst", "data protection analyst"],
        title_block_terms=["senior", "sr ", "sr.", "engineer", "director", "strategist", "hunter", "backend", "front end", "software"],
        location_allow_terms=["usa", "new york", "new jersey"],
        location_block_terms=["gbr", "united kingdom", "uk", "ireland", "japan", "india", "uae", "canada"],
        public_url_template="https://crowdstrike.wd5.myworkdayjobs.com/en-US/CrowdStrikeCareers{external_path}",
    ),
    build_source(
        name="CACI",
        source_type="workday",
        url="https://caci.wd1.myworkdayjobs.com/wday/cxs/caci/External/jobs",
        tags=["direct-careers", "gov-adjacent", "security", "hire-heavy"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="security",
        max_jobs=20,
        max_detail_fetches=20,
        search_terms=["security analyst", "cyber analyst", "service desk", "incident response"],
        title_allow_terms=["analyst", "service desk", "support", "it operator"],
        title_block_terms=["senior", "sr ", "sr.", "lead", "manager", "engineer", "architect", "linguist", "language", "exploitation", "forensics", "network access control", "devops"],
        location_allow_terms=["maryland", "virginia", "washington", "dc", "new jersey", "new york", "pennsylvania", "remote"],
        public_url_template="https://caci.wd1.myworkdayjobs.com/en-US/External{external_path}",
    ),
    build_source(
        name="KBR",
        source_type="workday",
        url="https://kbr.wd5.myworkdayjobs.com/wday/cxs/kbr/KBR_Careers/jobs",
        tags=["direct-careers", "gov-adjacent", "security", "enterprise"],
        difficulty="stretch",
        hiring_pattern="steady",
        industry="security",
        max_jobs=20,
        max_detail_fetches=20,
        search_terms=["cyber analyst", "security analyst", "technical support", "desktop support"],
        title_allow_terms=["analyst", "technical support", "desktop support", "support specialist"],
        title_block_terms=["senior", "sr ", "sr.", "manager", "engineer", "architect", "consultant", "isso", "sme", "specialist iv"],
        location_allow_terms=["maryland", "virginia", "washington", "dc", "new jersey", "new york", "pennsylvania", "massachusetts", "florida", "usa"],
        location_block_terms=["azerbaijan", "saudi", "iraq", "india", "singapore", "australia"],
        public_url_template="https://kbr.wd5.myworkdayjobs.com/en-US/KBR_Careers{external_path}",
    ),
    build_source(
        name="Travelers",
        source_type="workday",
        url="https://travelers.wd5.myworkdayjobs.com/wday/cxs/travelers/External/jobs",
        tags=["direct-careers", "enterprise", "insurance", "it", "nyc-friendly"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=20,
        max_detail_fetches=20,
        search_terms=["cyber", "incident", "service desk", "support", "technology intern"],
        title_allow_terms=[
            "cybersecurity ops",
            "technologist",
            "incident",
            "support",
            "service desk",
            "analyst",
            "technology intern",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "manager",
            "director",
            "underwriter",
            "attorney",
            "account executive",
            "specialist, liability",
            "software engineer",
            "data engineer",
        ],
        public_url_template="https://travelers.wd5.myworkdayjobs.com/en-US/External{external_path}",
    ),
    build_source(
        name="GovCIO",
        source_type="icims",
        url="https://careers-govcio.icims.com/jobs/search?ss=1&searchKeyword=security&in_iframe=1",
        search_urls=[
            "https://careers-govcio.icims.com/jobs/search?ss=1&searchKeyword=security&in_iframe=1",
            "https://careers-govcio.icims.com/jobs/search?ss=1&searchKeyword=information%20technology&in_iframe=1",
        ],
        tags=["direct-careers", "gov-adjacent", "security", "hire-heavy"],
        difficulty="realistic",
        hiring_pattern="hire-heavy",
        industry="security",
        max_jobs=30,
        max_detail_fetches=30,
        page_limit=4,
        title_allow_terms=[
            "security analyst",
            "incident handler",
            "technical analyst",
            "systems analyst",
            "support",
            "service desk",
            "help desk",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "manager",
            "director",
            "architect",
            "engineer",
            "sme",
            "developer",
            "project manager",
        ],
        location_allow_terms=[
            "us-",
            "remote",
            "washington",
            "virginia",
            "new york",
            "new jersey",
            "pennsylvania",
            "maryland",
        ],
        location_block_terms=[
            "kuwait",
            "saudi",
            "qatar",
            "jordan",
            "djibouti",
            "korea",
        ],
    ),
    build_source(
        name="Waters",
        source_type="icims",
        url="https://careers-waters.icims.com/jobs/search?ss=1&searchKeyword=security&in_iframe=1",
        search_urls=[
            "https://careers-waters.icims.com/jobs/search?ss=1&searchKeyword=security&in_iframe=1",
            "https://careers-waters.icims.com/jobs/search?ss=1&searchKeyword=identity&in_iframe=1",
            "https://careers-waters.icims.com/jobs/search?ss=1&searchKeyword=information%20technology&in_iframe=1",
        ],
        tags=["direct-careers", "enterprise", "security", "identity", "entry-friendly"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=20,
        max_detail_fetches=20,
        page_limit=3,
        title_allow_terms=[
            "identity",
            "access",
            "iam",
            "security analyst",
            "grc",
            "support",
            "intern",
            "administrator",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "principal",
            "manager",
            "director",
            "architect",
            "developer",
            "engineer",
        ],
        location_allow_terms=[
            "us",
            "united states",
            "new york",
            "massachusetts",
            "remote",
        ],
        location_block_terms=[
            "india",
            "singapore",
            "uk",
            "united kingdom",
            "ireland",
        ],
    ),
    build_source(
        name="Kimley-Horn",
        source_type="icims",
        url="https://careers-kimley-horn.icims.com/jobs/search?ss=1&searchKeyword=information%20technology&in_iframe=1",
        tags=["direct-careers", "enterprise", "it", "entry-friendly", "bridge"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=25,
        max_detail_fetches=25,
        page_limit=4,
        title_allow_terms=[
            "information technology intern",
            "information technology analyst",
            "technical support",
            "service desk",
            "desktop support",
            "systems analyst",
        ],
        title_block_terms=[
            "senior",
            "sr ",
            "sr.",
            "manager",
            "director",
            "architect",
            "engineer",
            "developer",
            "project manager",
            "surveyor",
            "planner",
            "recruiter",
            "landscape",
            "civil",
            "electrical",
            "mechanical",
        ],
        location_block_terms=[
            "canada",
            "india",
            "singapore",
            "uk",
            "united kingdom",
            "ireland",
        ],
    ),
    build_source(
        name="TierPoint",
        source_type="icims",
        url="https://careers-tierpoint.icims.com/jobs/search?ss=1&searchKeyword=operations&in_iframe=1",
        search_urls=[
            "https://careers-tierpoint.icims.com/jobs/search?ss=1&searchKeyword=operations&in_iframe=1",
            "https://careers-tierpoint.icims.com/jobs/search?ss=1&searchKeyword=information%20technology&in_iframe=1",
            "https://careers-tierpoint.icims.com/jobs/search?ss=1&searchKeyword=support&in_iframe=1",
            "https://careers-tierpoint.icims.com/jobs/search?ss=1&searchKeyword=security&in_iframe=1",
        ],
        tags=["direct-careers", "enterprise", "data-center", "entry-friendly", "local-ny"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=20,
        max_detail_fetches=20,
        page_limit=4,
        title_allow_terms=[
            "operations technician",
            "support",
            "service desk",
            "help desk",
            "security",
            "analyst",
            "technical",
            "it",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "director",
            "architect",
            "principal",
            "vice president",
            "sales support associate",
        ],
        location_allow_terms=[
            "new york",
            "ny",
            "hawthorne",
            "remote",
            "united states",
            "usa",
        ],
        location_block_terms=[
            "india",
            "singapore",
            "uk",
        ],
    ),
    build_source(
        name="Kraft Kennedy",
        source_type="workable",
        url="kraftkennedy",
        tags=["direct-careers", "workable", "msp", "security", "support", "entry-friendly", "remote-friendly"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="security",
        max_jobs=20,
        allow_in_combined_text=False,
        title_allow_terms=[
            "soc",
            "siem",
            "security analyst",
            "cloud support",
            "support infrastructure",
            "technical support",
            "support engineer",
            "help desk",
            "service desk",
            "it support",
            "systems",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "director",
            "sales",
            "account executive",
            "principal",
            "lead",
            "head of",
        ],
        location_allow_terms=[
            "united states",
            "usa",
            "remote",
            "new york",
            "ny",
        ],
        location_block_terms=[
            "india",
            "china",
            "philippines",
            "europe",
            "emea",
            "canada",
            "uk",
            "united kingdom",
            "australia",
            "mexico",
            "malaysia",
            "netherlands",
            "spain",
        ],
    ),
    build_source(
        name="Actionstep",
        source_type="workable",
        url="actionstep",
        tags=["direct-careers", "workable", "saas", "support", "entry-friendly", "remote-friendly"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=20,
        allow_in_combined_text=False,
        title_allow_terms=[
            "customer support analyst",
            "technical support",
            "product support",
            "application support",
            "support engineer",
            "help desk",
            "service desk",
            "it support",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "director",
            "sales",
            "account executive",
            "principal",
            "lead",
            "head of",
        ],
        location_allow_terms=[
            "united states",
            "usa",
            "remote",
            "new york",
            "ny",
        ],
        location_block_terms=[
            "india",
            "china",
            "philippines",
            "europe",
            "emea",
            "canada",
            "uk",
            "united kingdom",
            "australia",
            "mexico",
            "malaysia",
            "netherlands",
            "spain",
        ],
    ),
    build_source(
        name="Kate Farms",
        source_type="workable",
        url="kate-farms",
        tags=["direct-careers", "workable", "support", "entry-friendly", "remote-friendly"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=20,
        allow_in_combined_text=False,
        title_allow_terms=[
            "support specialist",
            "technical support",
            "product support",
            "application support",
            "customer support",
            "it support",
            "help desk",
            "service desk",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "director",
            "sales",
            "account executive",
            "principal",
            "lead",
            "head of",
        ],
        location_allow_terms=[
            "united states",
            "usa",
            "remote",
            "new york",
            "ny",
            "east coast",
        ],
        location_block_terms=[
            "india",
            "china",
            "philippines",
            "europe",
            "emea",
            "canada",
            "uk",
            "united kingdom",
            "australia",
            "mexico",
            "malaysia",
            "netherlands",
            "spain",
        ],
    ),
    build_source(
        name="InfoTrack US",
        source_type="workable",
        url="infotrack-us",
        tags=["direct-careers", "workable", "legal-tech", "support", "entry-friendly", "remote-friendly"],
        difficulty="realistic",
        hiring_pattern="steady",
        industry="tech",
        max_jobs=20,
        allow_in_combined_text=False,
        title_allow_terms=[
            "customer support specialist",
            "technical support",
            "product support",
            "application support",
            "support specialist",
            "support analyst",
            "help desk",
            "service desk",
            "it support",
        ],
        title_block_terms=[
            "senior",
            "manager",
            "director",
            "sales",
            "account executive",
            "principal",
            "lead",
            "head of",
            "contractor relations",
        ],
        location_allow_terms=[
            "united states",
            "usa",
            "remote",
            "new york",
            "ny",
        ],
        location_block_terms=[
            "india",
            "china",
            "philippines",
            "europe",
            "emea",
            "canada",
            "uk",
            "united kingdom",
            "australia",
            "mexico",
            "malaysia",
            "netherlands",
            "spain",
        ],
    ),
]
