"""Create a sanitized public copy of the job tool.

This script copies only public-safe source files, docs, and templates. It does
not copy resumes, tracker history, generated results, cache files, virtualenvs,
or Git metadata from the private working repo.
"""

from __future__ import annotations

import argparse
import shutil
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_TARGET = ROOT.parent / "job_tool_public"

SAFE_FILES = [
    ".gitattributes",
    ".gitignore",
    "CODEBASE_GUIDE.md",
    "PUBLIC_RELEASE_CHECKLIST.md",
    "README.md",
    "ROADMAP.md",
    "link_collector.py",
    "main.py",
    "mark_application.py",
    "requirements.txt",
    "resume_cyber.example.txt",
    "resume_it_support.example.txt",
    "scraper.py",
    "scripts/check_release_safety.py",
    "scripts/make_public_release.py",
    "scripts/smoke_test.py",
]

SAFE_DIRS = [
    ".github",
    "intake",
    "pipeline",
    "shared",
    "sources",
]

SAFE_RESULT_TEMPLATES = [
    "results/tracker/application_tracker.example.md",
]

BLOCKED_NAMES = {
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "jobs_cache.json",
    "resume_cyber.txt",
    "resume_it_support.txt",
}


def is_safe_target(target: Path) -> bool:
    """Protect against accidentally deleting the private working repo."""
    target = target.resolve()
    root = ROOT.resolve()
    return target != root and target.name.endswith("_public")


def copy_file(relative_path: str, target: Path, copied: list[str]) -> None:
    source_path = ROOT / relative_path
    if not source_path.exists():
        return
    destination_path = target / relative_path
    destination_path.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source_path, destination_path)
    copied.append(relative_path)


def copy_dir(relative_path: str, target: Path, copied: list[str]) -> None:
    source_dir = ROOT / relative_path
    if not source_dir.exists():
        return

    for source_path in source_dir.rglob("*"):
        if not source_path.is_file():
            continue
        if any(part in BLOCKED_NAMES for part in source_path.relative_to(ROOT).parts):
            continue
        if source_path.suffix == ".pyc":
            continue
        relative_file = source_path.relative_to(ROOT)
        destination_path = target / relative_file
        destination_path.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(source_path, destination_path)
        copied.append(str(relative_file).replace("\\", "/"))


def clean_target_contents(target: Path) -> None:
    """Delete generated public-copy contents while preserving the target repo metadata."""
    for child in target.iterdir():
        if child.name == ".git":
            continue
        if child.is_dir():
            shutil.rmtree(child)
        else:
            child.unlink()


def write_manifest(target: Path, copied: list[str]) -> None:
    lines = [
        "# Public Release Manifest",
        "",
        "This folder was generated by `scripts/make_public_release.py`.",
        "",
        "It intentionally excludes:",
        "",
        "- real resume files",
        "- real tracker files",
        "- generated results",
        "- diagnostics and archives",
        "- scrape cache",
        "- virtual environments",
        "- private-repo Git metadata",
        "",
        "## Copied Files",
        "",
        *[f"- `{path}`" for path in sorted(copied)],
        "",
    ]
    (target / "PUBLIC_RELEASE_MANIFEST.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a sanitized public copy of the job tool.")
    parser.add_argument("--target", default=str(DEFAULT_TARGET), help="Target folder for the sanitized copy.")
    parser.add_argument("--clean", action="store_true", help="Delete the target folder before copying.")
    args = parser.parse_args()

    target = Path(args.target).resolve()
    if not is_safe_target(target):
        raise SystemExit("Refusing to write target unless it is a separate folder ending in '_public'.")

    if args.clean and target.exists():
        clean_target_contents(target)

    target.mkdir(parents=True, exist_ok=True)

    copied: list[str] = []
    for relative_path in SAFE_FILES:
        copy_file(relative_path, target, copied)

    for relative_path in SAFE_DIRS:
        copy_dir(relative_path, target, copied)

    for relative_path in SAFE_RESULT_TEMPLATES:
        copy_file(relative_path, target, copied)

    write_manifest(target, copied)
    print(f"Public release copy written to: {target}")
    print(f"Copied {len(copied)} files.")


if __name__ == "__main__":
    main()
